#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define POWER_CHARGE_DETECT_PIN GPIO_NUM_21
#define POWER_ADC_UNIT ADC_UNIT_2
#define POWER_ADC_CHANNEL ADC_CHANNEL_3

// Active servo wiring
#define LEFT_FOOT_PIN GPIO_NUM_13//
#define LEFT_LEG_PIN GPIO_NUM_48// Xa
#define LEFT_HAND_PIN GPIO_NUM_47//GPIO_NUM_48  ?
#define RIGHT_FOOT_PIN GPIO_NUM_38// ngang GPIO_NUM_36 ? không dùng đc, dung ko lên
#define RIGHT_LEG_PIN GPIO_NUM_40//
#define RIGHT_HAND_PIN GPIO_NUM_39// ?

// Legacy servo wiring reference:
// RIGHT_LEG=39, RIGHT_FOOT=38, LEFT_LEG=17, LEFT_FOOT=18, LEFT_HAND=8, RIGHT_HAND=12

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

// Active TFT ST7789 1.54 wiring
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_17
#define DISPLAY_MOSI_PIN GPIO_NUM_41
#define DISPLAY_CLK_PIN GPIO_NUM_42
#define DISPLAY_DC_PIN GPIO_NUM_1
#define DISPLAY_RST_PIN GPIO_NUM_2
#define DISPLAY_CS_PIN GPIO_NUM_NC

// Legacy display wiring reference: BL=3, MOSI=10, CLK=9, DC=46, RST=11, CS=12
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 3

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define OTTO_ROBOT_VERSION "2.0.5"

#endif  // _BOARD_CONFIG_H_
